// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	UUID    string `gorm:"column:UUID" json:"UUID"`
	Name    string `gorm:"column:name" json:"name"`
	Age     int32  `gorm:"column:age" json:"age"`
	Version int32  `gorm:"column:version" json:"version"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
